
Vagrant.configure("2") do |config|
  config.vm.box_download_insecure = true
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8181, host: 8182
  config.vm.network "forwarded_port", guest: 8080, host: 8082
  config.vm.network "forwarded_port", guest: 4444, host: 4442
  config.vm.network "forwarded_port", guest: 4243, host: 4243

  config.vm.hostname = "selenoid"
  config.vm.post_up_message = "Selenoid is now started, go ahead and run your tests against http://localhost:4444/wd/hub and watch them using http://localhost:8080"

  config.vm.provider :virtualbox do |vb|
      vb.memory = "2048"
  end

  config.vm.provision "shell" do |s|
    s.path = 'master.sh'
  end
end
