
Vagrant.configure("2") do |config|
  config.vm.box_download_insecure = true
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.hostname = "Jenkins"
  config.vm.post_up_message = "Jenkins is now started, go ahead and watch data using http://localhost:8080"

  config.vm.provider :virtualbox do |vb|
      vb.memory = "4000"
  end

  config.vm.provision "shell" do |s|
    s.path = 'master.sh'
  end
end
